const foodDatabase = {
    // Fruits
    "apple": { calories: 95, protein: 0.5, carbs: 25, fat: 0.3, fiber: 4.4, sugar: 19, digestion: "30-40 min", digestionDesc: "Fruits digest quickly due to high water and simple sugar content", category: "fruit", kidneyImpact: "positive", kidneyTip: "Apples contain antioxidants that help reduce kidney inflammation and support overall kidney function." },
    "banana": { calories: 105, protein: 1.3, carbs: 27, fat: 0.4, fiber: 3.1, sugar: 14, digestion: "30-45 min", digestionDesc: "Bananas are easy to digest and provide quick energy", category: "fruit", kidneyImpact: "neutral", kidneyTip: "Bananas are moderate in potassium. Safe in normal amounts but monitor if you have kidney disease." },
    "orange": { calories: 62, protein: 1.2, carbs: 15, fat: 0.2, fiber: 3.1, sugar: 12, digestion: "30 min", digestionDesc: "Citrus fruits digest rapidly", category: "fruit", kidneyImpact: "positive", kidneyTip: "Oranges are rich in citrate which helps prevent kidney stone formation." },
    "strawberry": { calories: 49, protein: 1, carbs: 12, fat: 0.5, fiber: 3, sugar: 7, digestion: "25-35 min", digestionDesc: "Berries digest very quickly", category: "fruit", kidneyImpact: "positive", kidneyTip: "Strawberries are low in potassium and rich in antioxidants that protect kidney cells." },
    "grape": { calories: 104, protein: 1.1, carbs: 27, fat: 0.2, fiber: 1.4, sugar: 23, digestion: "30-40 min", digestionDesc: "Grapes are easy to digest when chewed well", category: "fruit", kidneyImpact: "positive", kidneyTip: "Grapes contain resveratrol which helps reduce oxidative stress on kidneys." },
    "watermelon": { calories: 46, protein: 0.9, carbs: 12, fat: 0.2, fiber: 0.6, sugar: 9, digestion: "20-30 min", digestionDesc: "Watermelon digests very quickly due to high water content", category: "fruit", kidneyImpact: "positive", kidneyTip: "Watermelon is 92% water and helps flush toxins from kidneys naturally." },
    "mango": { calories: 99, protein: 1.4, carbs: 25, fat: 0.6, fiber: 2.6, sugar: 23, digestion: "30-45 min", digestionDesc: "Mangoes digest moderately fast", category: "fruit", kidneyImpact: "neutral", kidneyTip: "Mangoes are moderate in potassium. Enjoy in moderation for kidney health." },
    "pineapple": { calories: 82, protein: 0.9, carbs: 22, fat: 0.2, fiber: 2.3, sugar: 16, digestion: "30-40 min", digestionDesc: "Pineapple contains enzymes that aid digestion", category: "fruit", kidneyImpact: "positive", kidneyTip: "Pineapple contains bromelain which helps reduce kidney inflammation." },
    "grapefruit": { calories: 52, protein: 1.7, carbs: 13, fat: 0.2, fiber: 2, sugar: 9, digestion: "30-40 min", digestionDesc: "Citrus fruits digest rapidly", category: "fruit", kidneyImpact: "positive", kidneyTip: "Grapefruit helps alkalize the body and supports kidney detoxification." },
    "pear": { calories: 101, protein: 0.6, carbs: 27, fat: 0.2, fiber: 5.5, sugar: 17, digestion: "30-40 min", digestionDesc: "Pears digest moderately quickly", category: "fruit", kidneyImpact: "positive", kidneyTip: "Pears are low in sodium and help reduce kidney stone risk." },

    // Vegetables
    "broccoli": { calories: 55, protein: 3.7, carbs: 11, fat: 0.6, fiber: 5.1, sugar: 2.2, digestion: "2-3 hours", digestionDesc: "Cruciferous vegetables take longer to digest", category: "vegetable", kidneyImpact: "positive", kidneyTip: "Broccoli helps detoxify harmful compounds and protects kidney cells from damage." },
    "carrot": { calories: 41, protein: 0.9, carbs: 10, fat: 0.2, fiber: 2.8, sugar: 4.7, digestion: "1.5-2 hours", digestionDesc: "Root vegetables digest moderately", category: "vegetable", kidneyImpact: "positive", kidneyTip: "Carrots are rich in vitamin A which helps prevent kidney stones." },
    "spinach": { calories: 23, protein: 2.9, carbs: 3.6, fat: 0.4, fiber: 2.2, sugar: 0.4, digestion: "1-2 hours", digestionDesc: "Leafy greens digest quickly", category: "vegetable", kidneyImpact: "negative", kidneyTip: "Spinach is very high in oxalates which can contribute to kidney stone formation." },
    "tomato": { calories: 22, protein: 1, carbs: 4.8, fat: 0.2, fiber: 1.5, sugar: 3.2, digestion: "30-60 min", digestionDesc: "Tomatoes digest relatively quickly", category: "vegetable", kidneyImpact: "neutral", kidneyTip: "Tomatoes are moderate in potassium. Safe in normal portions for healthy kidneys." },
    "cucumber": { calories: 16, protein: 0.7, carbs: 3.6, fat: 0.1, fiber: 0.5, sugar: 1.7, digestion: "30-60 min", digestionDesc: "High water content allows quick digestion", category: "vegetable", kidneyImpact: "positive", kidneyTip: "Cucumbers are excellent for kidneys - high water content helps flush toxins." },
    "potato": { calories: 161, protein: 4.3, carbs: 37, fat: 0.2, fiber: 3.8, sugar: 1.7, digestion: "2-3 hours", digestionDesc: "Starchy vegetables take longer to digest", category: "vegetable", kidneyImpact: "negative", kidneyTip: "Potatoes are very high in potassium which can stress weakened kidneys." },
    "sweet potato": { calories: 103, protein: 2.3, carbs: 24, fat: 0.1, fiber: 3.8, sugar: 7.4, digestion: "2-2.5 hours", digestionDesc: "Sweet potatoes digest slower than regular potatoes", category: "vegetable", kidneyImpact: "negative", kidneyTip: "Sweet potatoes are extremely high in potassium - limit if you have kidney issues." },
    "corn": { calories: 132, protein: 5, carbs: 29, fat: 1.5, fiber: 3.6, sugar: 6.3, digestion: "2-3 hours", digestionDesc: "Corn is harder to digest due to fibrous hull", category: "vegetable", kidneyImpact: "neutral", kidneyTip: "Corn is moderate in phosphorus. Safe in normal amounts for healthy kidneys." },
    "bell pepper": { calories: 31, protein: 1, carbs: 6, fat: 0.3, fiber: 2.1, sugar: 4.2, digestion: "30-60 min", digestionDesc: "Peppers digest relatively quickly", category: "vegetable", kidneyImpact: "positive", kidneyTip: "Bell peppers are low in potassium and rich in vitamin C which supports kidney health." },
    "lettuce": { calories: 15, protein: 1.4, carbs: 2.9, fat: 0.2, fiber: 1.3, sugar: 0.8, digestion: "20-30 min", digestionDesc: "Leafy greens digest very quickly", category: "vegetable", kidneyImpact: "positive", kidneyTip: "Lettuce is very low in potassium and helps keep kidneys hydrated." },
    "onion": { calories: 44, protein: 1.2, carbs: 10, fat: 0.1, fiber: 1.9, sugar: 4.7, digestion: "1-2 hours", digestionDesc: "Alliums digest moderately", category: "vegetable", kidneyImpact: "positive", kidneyTip: "Onions contain quercetin which helps protect kidneys from oxidative damage." },
    "celery": { calories: 16, protein: 0.7, carbs: 3, fat: 0.2, fiber: 1.6, sugar: 1.3, digestion: "20-30 min", digestionDesc: "High water content allows quick digestion", category: "vegetable", kidneyImpact: "positive", kidneyTip: "Celery is a natural diuretic that helps flush kidney toxins." },
    "mushroom": { calories: 22, protein: 3.1, carbs: 3.3, fat: 0.3, fiber: 1, sugar: 2, digestion: "1-2 hours", digestionDesc: "Mushrooms digest moderately", category: "vegetable", kidneyImpact: "neutral", kidneyTip: "Mushrooms are moderate in phosphorus. Safe in normal portions." },

    // Proteins
    "chicken breast": { calories: 165, protein: 31, carbs: 0, fat: 3.6, fiber: 0, sugar: 0, digestion: "3-4 hours", digestionDesc: "Lean protein takes several hours to fully digest", category: "protein", kidneyImpact: "neutral", kidneyTip: "Lean chicken is lower in phosphorus than red meat - a kidney-friendly protein choice." },
    "chicken thigh": { calories: 209, protein: 26, carbs: 0, fat: 11, fiber: 0, sugar: 0, digestion: "3-4 hours", digestionDesc: "Higher fat content slows digestion slightly", category: "protein", kidneyImpact: "neutral", kidneyTip: "Chicken thighs have more fat - consume in moderation for kidney health." },
    "beef steak": { calories: 271, protein: 26, carbs: 0, fat: 18, fiber: 0, sugar: 0, digestion: "4-5 hours", digestionDesc: "Red meat takes the longest to digest", category: "protein", kidneyImpact: "negative", kidneyTip: "Red meat is high in protein and phosphorus which can strain kidneys over time." },
    "ground beef": { calories: 254, protein: 17, carbs: 0, fat: 20, fiber: 0, sugar: 0, digestion: "4-5 hours", digestionDesc: "Ground beef digests slightly faster than steak", category: "protein", kidneyImpact: "negative", kidneyTip: "Ground beef is high in saturated fat and protein - limit for kidney health." },
    "pork chop": { calories: 231, protein: 25, carbs: 0, fat: 14, fiber: 0, sugar: 0, digestion: "3-4 hours", digestionDesc: "Pork digests faster than beef but slower than chicken", category: "protein", kidneyImpact: "negative", kidneyTip: "Pork is high in protein and sodium which can stress kidneys." },
    "salmon": { calories: 208, protein: 20, carbs: 0, fat: 13, fiber: 0, sugar: 0, digestion: "2.5-3 hours", digestionDesc: "Fish is easier to digest than red meat", category: "protein", kidneyImpact: "positive", kidneyTip: "Salmon's omega-3 fatty acids help reduce kidney inflammation and protect function." },
    "tuna": { calories: 130, protein: 29, carbs: 0, fat: 0.6, fiber: 0, sugar: 0, digestion: "2.5-3 hours", digestionDesc: "Lean fish digests relatively quickly", category: "protein", kidneyImpact: "neutral", kidneyTip: "Tuna is lean protein but high in mercury - consume in moderation." },
    "shrimp": { calories: 85, protein: 20, carbs: 0, fat: 0.2, fiber: 0, sugar: 0, digestion: "1.5-2 hours", digestionDesc: "Shellfish digests quickly", category: "protein", kidneyImpact: "neutral", kidneyTip: "Shrimp is low in fat but high in cholesterol - moderate portions recommended." },
    "egg": { calories: 78, protein: 6, carbs: 0.6, fat: 5, fiber: 0, sugar: 0.6, digestion: "2-3 hours", digestionDesc: "Eggs are moderately easy to digest", category: "protein", kidneyImpact: "neutral", kidneyTip: "Eggs are a good protein source but high in phosphorus - limit to 1-2 per day." },
    "tofu": { calories: 144, protein: 17, carbs: 3, fat: 9, fiber: 2, sugar: 1, digestion: "1.5-2 hours", digestionDesc: "Tofu is easier to digest than meat", category: "protein", kidneyImpact: "neutral", kidneyTip: "Tofu is plant-based protein but high in phosphorus - consume in moderation." },
    "bacon": { calories: 43, protein: 3, carbs: 0, fat: 3.5, fiber: 0, sugar: 0, digestion: "3-4 hours", digestionDesc: "Fatty meats take longer to digest", category: "protein", kidneyImpact: "negative", kidneyTip: "Bacon is very high in sodium and saturated fat - harmful to kidney health." },

    // Grains & Carbs
    "rice": { calories: 206, protein: 4.3, carbs: 45, fat: 0.4, fiber: 0.6, sugar: 0.1, digestion: "2-3 hours", digestionDesc: "White rice digests moderately", category: "grain", kidneyImpact: "positive", kidneyTip: "White rice is low in potassium and phosphorus - an excellent kidney-friendly grain." },
    "brown rice": { calories: 216, protein: 5, carbs: 45, fat: 1.8, fiber: 3.5, sugar: 0.7, digestion: "2.5-3.5 hours", digestionDesc: "Brown rice takes longer due to fiber content", category: "grain", kidneyImpact: "neutral", kidneyTip: "Brown rice is higher in phosphorus than white rice - moderate portions." },
    "bread": { calories: 79, protein: 2.7, carbs: 15, fat: 1, fiber: 0.6, sugar: 1.4, digestion: "1.5-2 hours", digestionDesc: "Bread digests relatively quickly", category: "grain", kidneyImpact: "positive", kidneyTip: "White bread is low in potassium and phosphorus - kidney-friendly choice." },
    "pasta": { calories: 220, protein: 8, carbs: 43, fat: 1.3, fiber: 2.5, sugar: 0.8, digestion: "2-3 hours", digestionDesc: "Pasta takes moderate time to digest", category: "grain", kidneyImpact: "positive", kidneyTip: "Pasta is low in potassium and provides good energy without kidney stress." },
    "noodles": { calories: 138, protein: 4.5, carbs: 25, fat: 2, fiber: 1.2, sugar: 0.6, digestion: "2-3 hours", digestionDesc: "Noodles digest moderately", category: "grain", kidneyImpact: "positive", kidneyTip: "Noodles are low in potassium and safe for kidney-friendly diets." },
    "oatmeal": { calories: 154, protein: 5.4, carbs: 27, fat: 2.6, fiber: 4, sugar: 0.6, digestion: "2-3 hours", digestionDesc: "Oatmeal provides sustained energy", category: "grain", kidneyImpact: "neutral", kidneyTip: "Oatmeal is moderate in phosphorus - safe in normal portions." },
    "cereal": { calories: 105, protein: 2.3, carbs: 24, fat: 0.3, fiber: 1.3, sugar: 10, digestion: "1.5-2 hours", digestionDesc: "Most cereals digest quickly", category: "grain", kidneyImpact: "neutral", kidneyTip: "Check labels - some cereals are high in sodium and phosphorus additives." },
    "tortilla": { calories: 104, protein: 2.8, carbs: 18, fat: 2.5, fiber: 1.1, sugar: 0.8, digestion: "1.5-2 hours", digestionDesc: "Tortillas digest relatively quickly", category: "grain", kidneyImpact: "positive", kidneyTip: "Flour tortillas are low in potassium - a kidney-friendly wrap option." },
    "bagel": { calories: 245, protein: 10, carbs: 48, fat: 1.5, fiber: 2, sugar: 5, digestion: "2-3 hours", digestionDesc: "Dense bread takes longer to digest", category: "grain", kidneyImpact: "neutral", kidneyTip: "Bagels are moderate in phosphorus due to higher protein content." },
    "pancake": { calories: 227, protein: 6.4, carbs: 28, fat: 10, fiber: 1, sugar: 4, digestion: "2-3 hours", digestionDesc: "Pancakes digest moderately", category: "grain", kidneyImpact: "neutral", kidneyTip: "Pancakes are moderate - watch portion sizes and toppings for kidney health." },
    "waffle": { calories: 218, protein: 6, carbs: 25, fat: 11, fiber: 1, sugar: 3, digestion: "2-3 hours", digestionDesc: "Waffles digest similarly to pancakes", category: "grain", kidneyImpact: "neutral", kidneyTip: "Waffles are moderate - limit syrup and butter for better kidney health." },

    // Dairy
    "milk": { calories: 149, protein: 8, carbs: 12, fat: 8, fiber: 0, sugar: 12, digestion: "1.5-2 hours", digestionDesc: "Milk digests moderately", category: "dairy", kidneyImpact: "negative", kidneyTip: "Milk is high in calcium and phosphorus which can stress kidneys." },
    "cheese": { calories: 113, protein: 7, carbs: 0.4, fat: 9, fiber: 0, sugar: 0.1, digestion: "3-4 hours", digestionDesc: "Cheese takes longer to digest due to fat content", category: "dairy", kidneyImpact: "negative", kidneyTip: "Cheese is very high in sodium and phosphorus - limit for kidney health." },
    "yogurt": { calories: 100, protein: 17, carbs: 6, fat: 0.7, fiber: 0, sugar: 6, digestion: "1-2 hours", digestionDesc: "Yogurt is easier to digest than milk", category: "dairy", kidneyImpact: "neutral", kidneyTip: "Greek yogurt is high in protein but also phosphorus - moderate portions." },
    "butter": { calories: 102, protein: 0.1, carbs: 0, fat: 12, fiber: 0, sugar: 0, digestion: "3-4 hours", digestionDesc: "Pure fat takes longer to digest", category: "dairy", kidneyImpact: "neutral", kidneyTip: "Butter is low in protein but high in saturated fat - use sparingly." },
    "ice cream": { calories: 207, protein: 3.5, carbs: 24, fat: 11, fiber: 0, sugar: 21, digestion: "2-3 hours", digestionDesc: "High sugar and fat slow digestion", category: "dairy", kidneyImpact: "negative", kidneyTip: "Ice cream is high in phosphorus, potassium, and sugar - limit for kidneys." },

    // Fast Food
    "burger": { calories: 354, protein: 20, carbs: 31, fat: 17, fiber: 1.5, sugar: 7, digestion: "4-5 hours", digestionDesc: "Combination of meat, bread, and fat slows digestion", category: "fastfood", kidneyImpact: "negative", kidneyTip: "Burgers are high in sodium, protein, and saturated fat - stressful for kidneys." },
    "pizza": { calories: 285, protein: 12, carbs: 36, fat: 10, fiber: 2.3, sugar: 3.6, digestion: "3-4 hours", digestionDesc: "Pizza is heavy and takes time to digest", category: "fastfood", kidneyImpact: "negative", kidneyTip: "Pizza is very high in sodium and phosphorus from cheese - limit intake." },
    "french fries": { calories: 365, protein: 4, carbs: 48, fat: 17, fiber: 4, sugar: 0.3, digestion: "3-4 hours", digestionDesc: "Fried foods take longer to digest", category: "fastfood", kidneyImpact: "negative", kidneyTip: "Fries are high in sodium and unhealthy fats - harmful to kidney function." },
    "hot dog": { calories: 290, protein: 10, carbs: 24, fat: 17, fiber: 1, sugar: 4, digestion: "3-4 hours", digestionDesc: "Processed meats digest slowly", category: "fastfood", kidneyImpact: "negative", kidneyTip: "Hot dogs are processed meat high in sodium - strongly limit for kidney health." },
    "chicken nuggets": { calories: 280, protein: 14, carbs: 18, fat: 17, fiber: 1, sugar: 0.5, digestion: "3-4 hours", digestionDesc: "Fried chicken takes longer to digest", category: "fastfood", kidneyImpact: "negative", kidneyTip: "Nuggets are fried and processed - high in sodium and unhealthy fats." },
    "taco": { calories: 226, protein: 9, carbs: 20, fat: 12, fiber: 2, sugar: 2, digestion: "3-4 hours", digestionDesc: "Tacos digest moderately", category: "fastfood", kidneyImpact: "negative", kidneyTip: "Tacos can be high in sodium from seasoning - limit for kidney health." },
    "burrito": { calories: 487, protein: 21, carbs: 56, fat: 20, fiber: 8, sugar: 4, digestion: "4-5 hours", digestionDesc: "Large meals take longer to digest", category: "fastfood", kidneyImpact: "negative", kidneyTip: "Burritos are very high in sodium, protein, and phosphorus - heavy on kidneys." },
    "sandwich": { calories: 300, protein: 15, carbs: 35, fat: 12, fiber: 3, sugar: 5, digestion: "3-4 hours", digestionDesc: "Sandwiches digest moderately", category: "fastfood", kidneyImpact: "neutral", kidneyTip: "Sandwiches vary - choose low-sodium options for better kidney health." },

    // Snacks
    "chips": { calories: 536, protein: 7, carbs: 53, fat: 35, fiber: 4.4, sugar: 0.3, digestion: "2-3 hours", digestionDesc: "Fried snacks digest slowly", category: "snack", kidneyImpact: "negative", kidneyTip: "Chips are extremely high in sodium which directly damages kidney function." },
    "popcorn": { calories: 31, protein: 1, carbs: 6, fat: 0.4, fiber: 1.2, sugar: 0.1, digestion: "1.5-2 hours", digestionDesc: "Popcorn is a whole grain snack", category: "snack", kidneyImpact: "positive", kidneyTip: "Popcorn is low in sodium and phosphorus - a kidney-friendly snack choice." },
    "pretzels": { calories: 380, protein: 10, carbs: 79, fat: 3, fiber: 3, sugar: 3, digestion: "2-3 hours", digestionDesc: "Pretzels digest moderately", category: "snack", kidneyImpact: "negative", kidneyTip: "Pretzels are very high in sodium - bad for kidney and heart health." },
    "nuts": { calories: 173, protein: 5, carbs: 6, fat: 16, fiber: 2, sugar: 1, digestion: "3-4 hours", digestionDesc: "Nuts take time due to high fat content", category: "snack", kidneyImpact: "neutral", kidneyTip: "Nuts are high in phosphorus and potassium - limit small handful portions." },
    "peanut butter": { calories: 188, protein: 8, carbs: 6, fat: 16, fiber: 2, sugar: 3, digestion: "3-4 hours", digestionDesc: "Nut butters digest slowly", category: "snack", kidneyImpact: "neutral", kidneyTip: "Peanut butter is high in phosphorus - moderate 1 tablespoon portions." },
    "crackers": { calories: 137, protein: 3, carbs: 17, fat: 6, fiber: 0.6, sugar: 0.5, digestion: "1.5-2 hours", digestionDesc: "Crackers digest relatively quickly", category: "snack", kidneyImpact: "neutral", kidneyTip: "Check labels - some crackers have added sodium and phosphorus." },
    "granola bar": { calories: 190, protein: 3, carbs: 29, fat: 7, fiber: 2, sugar: 12, digestion: "2-3 hours", digestionDesc: "Granola bars digest moderately", category: "snack", kidneyImpact: "neutral", kidneyTip: "Granola bars vary - choose low-sugar options for kidney health." },
    "chocolate": { calories: 546, protein: 5, carbs: 60, fat: 31, fiber: 7, sugar: 48, digestion: "3-4 hours", digestionDesc: "Chocolate is high in fat and sugar", category: "snack", kidneyImpact: "negative", kidneyTip: "Chocolate is high in potassium, phosphorus, and sugar - limit for kidneys." },

    // Soups & Stews
    "soup": { calories: 75, protein: 4, carbs: 10, fat: 2, fiber: 1, sugar: 2, digestion: "1-2 hours", digestionDesc: "Soups digest quickly due to liquid content", category: "soup", kidneyImpact: "neutral", kidneyTip: "Soups vary - choose low-sodium broths for kidney-friendly options." },
    "chili": { calories: 250, protein: 15, carbs: 20, fat: 12, fiber: 6, sugar: 4, digestion: "3-4 hours", digestionDesc: "Hearty soups take longer to digest", category: "soup", kidneyImpact: "negative", kidneyTip: "Chili is high in sodium, protein, and potassium - limit for kidney health." },
    "ramen": { calories: 436, protein: 15, carbs: 55, fat: 16, fiber: 2, sugar: 4, digestion: "2.5-3.5 hours", digestionDesc: "Ramen digests moderately", category: "soup", kidneyImpact: "negative", kidneyTip: "Ramen is extremely high in sodium from broth - very hard on kidneys." },

    // Beverages
    "coffee": { calories: 2, protein: 0.3, carbs: 0, fat: 0, fiber: 0, sugar: 0, digestion: "15-30 min", digestionDesc: "Coffee passes through quickly", category: "beverage", kidneyImpact: "neutral", kidneyTip: "Coffee in moderation (1-2 cups) is fine but can cause dehydration." },
    "tea": { calories: 2, protein: 0, carbs: 0.5, fat: 0, fiber: 0, sugar: 0, digestion: "15-30 min", digestionDesc: "Tea digests very quickly", category: "beverage", kidneyImpact: "positive", kidneyTip: "Green tea is rich in antioxidants that help protect kidney cells from damage." },
    "juice": { calories: 112, protein: 0.5, carbs: 28, fat: 0.3, fiber: 0.2, sugar: 24, digestion: "20-30 min", digestionDesc: "Juice digests quickly due to lack of fiber", category: "beverage", kidneyImpact: "neutral", kidneyTip: "Fruit juice is high in sugar and potassium - dilute and limit portions." },
    "soda": { calories: 140, protein: 0, carbs: 39, fat: 0, fiber: 0, sugar: 39, digestion: "20-30 min", digestionDesc: "Sugar water digests very quickly", category: "beverage", kidneyImpact: "negative", kidneyTip: "Soda is very high in sugar and phosphoric acid - damages kidney function." },
    "smoothie": { calories: 200, protein: 5, carbs: 40, fat: 3, fiber: 4, sugar: 30, digestion: "30-45 min", digestionDesc: "Blended fruit digests quickly", category: "beverage", kidneyImpact: "neutral", kidneyTip: "Smoothies can be high in potassium from fruits - watch ingredients." },
    "beer": { calories: 154, protein: 1.6, carbs: 13, fat: 0, fiber: 0, sugar: 1, digestion: "30-60 min", digestionDesc: "Alcohol absorbs quickly", category: "beverage", kidneyImpact: "negative", kidneyTip: "Alcohol dehydrates kidneys and impairs their filtering function over time." },
    "wine": { calories: 125, protein: 0.1, carbs: 3.4, fat: 0, fiber: 0, sugar: 1, digestion: "30-60 min", digestionDesc: "Wine absorbs relatively quickly", category: "beverage", kidneyImpact: "negative", kidneyTip: "Alcohol stresses kidneys and can lead to dehydration and kidney damage." },

    // Common Meals
    "sushi": { calories: 200, protein: 8, carbs: 38, fat: 1, fiber: 0.5, sugar: 4, digestion: "2-3 hours", digestionDesc: "Sushi digests moderately", category: "meal", kidneyImpact: "neutral", kidneyTip: "Sushi is moderate - soy sauce is very high in sodium so use sparingly." },
    "fried rice": { calories: 343, protein: 9, carbs: 44, fat: 15, fiber: 1.5, sugar: 1, digestion: "3-4 hours", digestionDesc: "Fried rice takes longer due to oil", category: "meal", kidneyImpact: "negative", kidneyTip: "Fried rice is high in sodium from soy sauce and oil - limit for kidneys." },
    "curry": { calories: 280, protein: 15, carbs: 25, fat: 14, fiber: 4, sugar: 3, digestion: "3-4 hours", digestionDesc: "Curry digests moderately", category: "meal", kidneyImpact: "negative", kidneyTip: "Curry is often high in sodium and spices which can stress kidneys." },
    "stir fry": { calories: 250, protein: 18, carbs: 15, fat: 14, fiber: 3, sugar: 4, digestion: "3-4 hours", digestionDesc: "Stir fry digests moderately", category: "meal", kidneyImpact: "neutral", kidneyTip: "Stir fry can be kidney-friendly with low-sodium sauce and fresh vegetables." },
    "spaghetti": { calories: 220, protein: 8, carbs: 43, fat: 1.3, fiber: 2.5, sugar: 0.8, digestion: "2-3 hours", digestionDesc: "Pasta dishes digest moderately", category: "meal", kidneyImpact: "positive", kidneyTip: "Pasta with light sauce is kidney-friendly - low in potassium and phosphorus." },
    "lasagna": { calories: 336, protein: 21, carbs: 24, fat: 18, fiber: 2, sugar: 5, digestion: "4-5 hours", digestionDesc: "Heavy layered dishes take longer", category: "meal", kidneyImpact: "negative", kidneyTip: "Lasagna is very high in sodium, protein, and phosphorus from cheese." },
    "tacos": { calories: 226, protein: 9, carbs: 20, fat: 12, fiber: 2, sugar: 2, digestion: "3-4 hours", digestionDesc: "Tacos digest moderately", category: "meal", kidneyImpact: "negative", kidneyTip: "Tacos can be high in sodium from seasoning - limit for kidney health." },
    "fried chicken": { calories: 320, protein: 21, carbs: 12, fat: 22, fiber: 0.5, sugar: 0.5, digestion: "4-5 hours", digestionDesc: "Fried chicken is heavy and takes time", category: "meal", kidneyImpact: "negative", kidneyTip: "Fried chicken is high in sodium, fat, and protein - hard on kidneys." },
    "grilled cheese": { calories: 370, protein: 15, carbs: 28, fat: 23, fiber: 1.5, sugar: 3, digestion: "3-4 hours", digestionDesc: "Grilled cheese is moderately heavy", category: "meal", kidneyImpact: "negative", kidneyTip: "Grilled cheese is high in sodium and phosphorus from cheese." },
    "steak": { calories: 271, protein: 26, carbs: 0, fat: 18, fiber: 0, sugar: 0, digestion: "4-5 hours", digestionDesc: "Steak takes the longest to digest", category: "meal", kidneyImpact: "negative", kidneyTip: "Steak is very high in protein and phosphorus - limit for kidney health." },

    // Desserts
    "cake": { calories: 352, protein: 5, carbs: 52, fat: 15, fiber: 1, sugar: 34, digestion: "3-4 hours", digestionDesc: "Cakes take longer due to sugar and fat", category: "dessert", kidneyImpact: "negative", kidneyTip: "Cake is high in sugar, phosphorus, and potassium - limit for kidneys." },
    "cookie": { calories: 148, protein: 2, carbs: 19, fat: 7, fiber: 0.5, sugar: 10, digestion: "2-3 hours", digestionDesc: "Cookies digest moderately", category: "dessert", kidneyImpact: "negative", kidneyTip: "Cookies are high in sugar and phosphorus - enjoy occasionally." },
    "brownie": { calories: 466, protein: 5, carbs: 62, fat: 24, fiber: 2, sugar: 42, digestion: "3-4 hours", digestionDesc: "Brownies are dense and take time", category: "dessert", kidneyImpact: "negative", kidneyTip: "Brownies are very high in sugar and fat - limit for kidney health." },
    "donut": { calories: 269, protein: 3.5, carbs: 31, fat: 15, fiber: 0.8, sugar: 13, digestion: "2-3 hours", digestionDesc: "Donuts digest moderately", category: "dessert", kidneyImpact: "negative", kidneyTip: "Donuts are fried and high in sugar and sodium - bad for kidneys." },
    "pie": { calories: 411, protein: 5, carbs: 55, fat: 20, fiber: 2, sugar: 30, digestion: "3-4 hours", digestionDesc: "Pies take longer to digest", category: "dessert", kidneyImpact: "negative", kidneyTip: "Pie is high in sugar and fat - limit portions for kidney health." },

    // Legumes
    "beans": { calories: 127, protein: 8.7, carbs: 23, fat: 0.5, fiber: 7.4, sugar: 0.6, digestion: "2-3 hours", digestionDesc: "Beans are high in fiber and protein", category: "legume", kidneyImpact: "negative", kidneyTip: "Beans are very high in potassium, phosphorus, and protein - limit for kidneys." },
    "lentils": { calories: 116, protein: 9, carbs: 20, fat: 0.4, fiber: 8, sugar: 1.8, digestion: "2-3 hours", digestionDesc: "Lentils digest moderately", category: "legume", kidneyImpact: "negative", kidneyTip: "Lentils are high in potassium and phosphorus - moderate small portions." },
    "chickpeas": { calories: 164, protein: 8.9, carbs: 27, fat: 2.6, fiber: 7.6, sugar: 4.8, digestion: "2-3 hours", digestionDesc: "Chickpeas digest moderately", category: "legume", kidneyImpact: "negative", kidneyTip: "Chickpeas are high in potassium and phosphorus - limit for kidney health." },
    "hummus": { calories: 166, protein: 8, carbs: 14, fat: 10, fiber: 6, sugar: 0.2, digestion: "2-3 hours", digestionDesc: "Hummus digests moderately", category: "legume", kidneyImpact: "neutral", kidneyTip: "Hummus is moderate - small portions with vegetables is kidney-friendly." },

    // Nuts & Seeds
    "almonds": { calories: 164, protein: 6, carbs: 6, fat: 14, fiber: 3.5, sugar: 1.2, digestion: "3-4 hours", digestionDesc: "Nuts take time due to healthy fats", category: "nut", kidneyImpact: "neutral", kidneyTip: "Almonds are high in phosphorus - limit to a small handful." },
    "cashews": { calories: 157, protein: 5, carbs: 9, fat: 12, fiber: 0.9, sugar: 1.7, digestion: "3-4 hours", digestionDesc: "Cashews digest slowly", category: "nut", kidneyImpact: "neutral", kidneyTip: "Cashews are moderate in phosphorus - enjoy in small portions." },
    "walnuts": { calories: 185, protein: 4.3, carbs: 3.9, fat: 18, fiber: 1.9, sugar: 0.7, digestion: "3-4 hours", digestionDesc: "Walnuts digest slowly", category: "nut", kidneyImpact: "positive", kidneyTip: "Walnuts contain omega-3s that help reduce kidney inflammation." },
    "peanuts": { calories: 161, protein: 7.3, carbs: 4.6, fat: 14, fiber: 2.4, sugar: 1.3, digestion: "3-4 hours", digestionDesc: "Peanuts digest slowly", category: "nut", kidneyImpact: "neutral", kidneyTip: "Peanuts are moderate in phosphorus - limit small portions." }
};

// Search function
function searchFood(query) {
    query = query.toLowerCase().trim();
    const matches = [];
    
    for (const [name, data] of Object.entries(foodDatabase)) {
        if (name.includes(query)) {
            matches.push({ name, ...data });
        }
    }
    
    // Sort by relevance (exact match first)
    matches.sort((a, b) => {
        const aExact = a.name === query ? 0 : 1;
        const bExact = b.name === query ? 0 : 1;
        if (aExact !== bExact) return aExact - bExact;
        return a.name.localeCompare(b.name);
    });
    
    return matches.slice(0, 10);
}
